### ISSUE TITLE
Incorrect Library name 

### ISSUE THREAD

**Issue by siavashre** [pingchen09990102/BNSIM#1]
In BMSIM.pl file in line 12 to 15 there is 3 package that imported but their name is inconsistent with the package name in the lib directory. So, 'use ErrorFN' should change to 'use FN', 'use ErrorFP' change to 'use FP' and 'use ErrorStretch' change to 'use Stretch'.

**Comment by pingchen09990102** [comment]
Thank you very much! I have uploaded the new BMSIM.pl file. You can try the new script with the example files.
